# Generated by Django 5.1.7 on 2025-04-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_recipe_cuisines_recipe_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cuisine',
            new_name='cuisines',
        ),
    ]
