# Generated by Django 5.0.7 on 2024-07-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuisine_ingredient_recipe_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
