# Generated by Django 5.1.7 on 2025-04-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_cuisines_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipe_images/default-image.png', null=True, upload_to='recipe_images/'),
        ),
    ]
