# Generated by Django 5.0.7 on 2024-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_ingredient_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='recipe_images/'),
        ),
    ]
